baseURL = 'https://mumaniu.cn/'
languageCode = 'zh-cn'
title = '牧码牛的博客'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
mainSections = ['posts']
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"
